In [ ]:
  from google.colab import drive
import pandas as pd
drive.mount('/content/drive')


import os
os.chdir('/content/drive/MyDrive/data_campus_prj/labeling')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('stock_price.csv')
df

,stock_id,date,closing_price,market_price,high_price,low_price
0,80,2023-04-28,22250.0,22050.0,22300.0,21950.0
1,80,2023-05-02,22500.0,22250.0,22650.0,22250.0
2,80,2023-05-03,22400.0,22550.0,22700.0,22350.0
3,80,2023-05-04,22500.0,22400.0,22700.0,22250.0
4,80,2023-05-08,22700.0,22550.0,22750.0,22500.0
...,...,...,...,...,...,...
12995,402340,2023-07-27,45700.0,43100.0,46150.0,43000.0
12996,402340,2023-07-28,45400.0,44900.0,45800.0,44300.0
12997,402340,2023-07-31,44400.0,45200.0,45450.0,43500.0
12998,402340,2023-08-01,45400.0,43850.0,45400.0,43550.0
12999,402340,2023-08-02,44900.0,44800.0,45900.0,44400.0

In [ ]:
df['date'] = pd.to_datetime(df['date'])  # Convert 'date' column to datetime if it's not already

# Sort the DataFrame by stock_id and date in descending order
sorted_df = df.sort_values(by=['stock_id', 'date'], ascending=[True, False])
df = sorted_df.reset_index(drop=True)
df

       stock_id       date  closing_price  market_price  high_price  low_price
0            80 2023-08-02        20300.0       20600.0     20700.0    20250.0
1            80 2023-08-01        20550.0       20350.0     20700.0    20250.0
2            80 2023-07-31        20300.0       20250.0     20700.0    20150.0
3            80 2023-07-28        20050.0       20000.0     20250.0    19920.0
4            80 2023-07-27        20250.0       19150.0     20250.0    19150.0
...         ...        ...            ...           ...         ...        ...
12995    402340 2023-05-08        42100.0       42100.0     42400.0    41750.0
12996    402340 2023-05-04        41800.0       41500.0     42300.0    41350.0
12997    402340 2023-05-03        41750.0       41200.0     42050.0    41200.0
12998    402340 2023-05-02        41350.0       42500.0     42500.0    40500.0
12999    402340 2023-04-28        42450.0       40450.0     42550.0    40450.0

[13000 rows x 6 columns]

In [ ]:
df.isnull().sum()

stock_id         0
date             0
closing_price    0
market_price     0
high_price       0
low_price        0
dtype: int64

In [ ]:
from tqdm import tqdm
import datetime
for i in tqdm(range(0,len(df),65)):
  for j in range(65):
    if df.loc[i+j][1] == datetime.date(2023,4,28):
      df.loc[i+j, 'label1'] = -1
      continue
    if df.loc[i+j][3] <= df.loc[i+j][2]:
      df.loc[i+j, 'label1'] = 1
    elif df.loc[i+j][3] > df.loc[i+j][2]:
      df.loc[i+j, 'label1'] = 0

  0%|          | 0/200 [00:00<?, ?it/s]<ipython-input-81-3a9bb6ae5b6b>:5: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if df.loc[i+j][1] == datetime.date(2023,4,28):
<ipython-input-81-3a9bb6ae5b6b>:5: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if df.loc[i+j][1] == datetime.date(2023,4,28):
100%|██████████| 200/200 [00:08<00:00, 22.50it/s]

In [ ]:
from tqdm import tqdm_pandas, tqdm
import datetime
for i in tqdm(range(0, len(df), 65)):
    for j in range(65):
         if df.loc[i+j][1] == datetime.date(2023, 4, 28):
             df.loc[i+j, 'label2'] = -1
             continue
         if df.loc[i+j][3] < df.loc[i+j+1][2]:
             df.loc[i+j, 'label2'] = 0
         elif df.loc[i+j][3] >= df.loc[i+j+1][2]:
             df.loc[i+j, 'label2'] = 1

  0%|          | 0/200 [00:00<?, ?it/s]<ipython-input-82-9de1aeef6ec9>:5: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if df.loc[i+j][1] == datetime.date(2023, 4, 28):
<ipython-input-82-9de1aeef6ec9>:5: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if df.loc[i+j][1] == datetime.date(2023, 4, 28):
100%|██████████| 200/200 [00:11<00:00, 17.15it/s]

In [ ]:
df.isnull().sum()

stock_id         0
date             0
closing_price    0
market_price     0
high_price       0
low_price        0
label1           0
label2           0
dtype: int64

In [ ]:

df['label1'] = df.label1.astype('int64')
df['label2'] = df.label2.astype('int64')
df

,stock_id,date,closing_price,market_price,high_price,low_price,label1,label2
0,80,2023-08-02,20300.0,20600.0,20700.0,20250.0,0,1
1,80,2023-08-01,20550.0,20350.0,20700.0,20250.0,1,1
2,80,2023-07-31,20300.0,20250.0,20700.0,20150.0,1,1
3,80,2023-07-28,20050.0,20000.0,20250.0,19920.0,1,0
4,80,2023-07-27,20250.0,19150.0,20250.0,19150.0,1,0
...,...,...,...,...,...,...,...,...
12995,402340,2023-05-08,42100.0,42100.0,42400.0,41750.0,1,1
12996,402340,2023-05-04,41800.0,41500.0,42300.0,41350.0,1,0
12997,402340,2023-05-03,41750.0,41200.0,42050.0,41200.0,1,0
12998,402340,2023-05-02,41350.0,42500.0,42500.0,40500.0,0,1
12999,402340,2023-04-28,42450.0,40450.0,42550.0,40450.0,-1,-1

In [ ]:
df.to_csv("labeled_stock_prices.csv")

# 뉴스 라벨링 예제

In [ ]:
news = pd.read_csv('han_df2.csv')
news['text'][0]

In [ ]:
import datetime
from datetime import timedelta

for i in tqdm(range(len(news))):
    news_date_str = news.loc[i][2]  # 날짜 문자열 가져오기
    news_date = datetime.datetime.strptime(news_date_str, "%Y-%m-%d")  # 문자열을 datetime 개체로 변환 (시간 정보 제외)
    if len(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]) == 0:
        for j in range(1, 7):
            next_date = news_date + timedelta(days=j)
            next_date_str = next_date.strftime("%Y-%m-%d")  # 다음 날짜를 문자열 형식으로 변환
            next_date_df = df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == next_date_str)]
            if len(next_date_df) == 0 or next_date_df['label2'].isnull().any():
                continue
            news.loc[i, 'label'] = int(next_date_df['label2'])
        continue
    if news.loc[i][2].weekday() == 4:
        if news.loc[i][2].time() > datetime.time(18, 0):
            for j in range(1, 7):
                next_date = news_date + timedelta(days=j)
                next_date_str = next_date.strftime("%Y-%m-%d")  # 다음 날짜를 문자열 형식으로 변환
                next_date_df = df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == next_date_str)]
                if len(next_date_df) == 0 or next_date_df['label2'].isnull().any():
                    continue
                news.loc[i, 'label'] = int(next_date_df['label2'])
        else:
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label1'])
    else:
        if news.loc[i][2].time() > datetime.time(18):
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label2'])
        else:
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label1'])

100%|██████████| 132351/132351 [20:52<00:00, 105.67it/s]

In [ ]:
news.to_csv("labeled_token_news.csv")

In [ ]:
import pandas as pd

# 뉴스 라벨링 찐

In [ ]:
news = pd.read_csv('han_df2.csv')
news = news.drop(news.columns[[0,1]], axis=1)

In [ ]:
import datetime
from datetime import timedelta

for i in tqdm(range(len(news))):
    news_date_str = news.loc[i][2]  # 날짜 문자열 가져오기
    news_date = datetime.datetime.strptime(news_date_str, "%Y-%m-%d")  # 문자열을 datetime 개체로 변환 (시간 정보 제외)
    if len(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]) == 0:
        for j in range(1, 7):
            next_date = news_date + timedelta(days=j)
            next_date_str = next_date.strftime("%Y-%m-%d")  # 다음 날짜를 문자열 형식으로 변환
            next_date_df = df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == next_date_str)]
            if len(next_date_df) == 0 or next_date_df['label2'].isnull().any():
                continue
            news.loc[i, 'label'] = int(next_date_df['label2'])
        continue
    if news.loc[i][2].weekday() == 4:
        if news.loc[i][2].time() > datetime.time(18, 0):
            for j in range(1, 7):
                next_date = news_date + timedelta(days=j)
                next_date_str = next_date.strftime("%Y-%m-%d")  # 다음 날짜를 문자열 형식으로 변환
                next_date_df = df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == next_date_str)]
                if len(next_date_df) == 0 or next_date_df['label2'].isnull().any():
                    continue
                news.loc[i, 'label'] = int(next_date_df['label2'])
        else:
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label1'])
    else:
        if news.loc[i][2].time() > datetime.time(18):
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label2'])
        else:
            news.loc[i, 'label'] = int(df.loc[(df["stock_id"] == news.loc[i][0]) & (df["date"] == news_date.date())]['label1'])

100%|██████████| 132337/132337 [18:52<00:00, 116.90it/s]

In [ ]:
news['label'].isnull().sum()

1

In [ ]:
news.isnull().sum()

stock_id            0
text                0
date                0
token               0
stopword_tokened    0
stock_name          0
category            0
label               1
dtype: int64

In [ ]:
rows_with_nan = news[news.isna().any(axis=1)]
rows_with_nan

,stock_id,text,date,token,stopword_tokened,stock_name,category,label
126990,373220,1 All rights reserved 무단 전재 및 재배포 금지 보수성향의 윤석...,2023-08-02,"바, 세액공제, 재정분담, 기술, 며, 관행, 뒤지, 기업, 초, 의문, 관광객, ...","바, 세액공제, 재정분담, 기술, 며, 관행, 뒤지, 기업, 초, 의문, 관광객, ...",LG에너지솔루션,산업재,NaN

In [ ]:
news = news.dropna(axis=0)

In [ ]:
news['label'] = news.label.astype('int64')
news

<ipython-input-108-d7720708bbce>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news['label'] = news.label.astype('int64')

,stock_id,text,date,token,stopword_tokened,stock_name,category,label
0,80,안호근 한국농업기술진흥원 원장 안호근 한국농업기술진흥원 원장은 첨단기술에 기반한 농...,2023-07-31,"개최, 바, 미간, 기업홍보, 유입, 활동, 활발, 유통산업, 기술, 며, 기획, ...","개최, 바, 미간, 기업홍보, 유입, 활동, 활발, 유통산업, 기술, 며, 기획, ...",하이트진로,생활소비재,1
1,80,김성희 고려대 노동대학원 교수 한국 불안정한 노사관계 심각한 수준 취약계층 중심의...,2023-07-31,"나서, 벌, 관행, 기업, 안정성, 특고다, 투, 언급, 제도개선, 청구, 최대, ...","나서, 벌, 관행, 기업, 안정성, 특고다, 투, 언급, 제도개선, 청구, 최대, ...",하이트진로,생활소비재,1
2,80,내수용은 공장 출고가 수출용은 평균 계약단가 기준 내수용 출고가에 관세 주세 교육세...,2023-07-31,"기준, 45, 바, 차, 부가세, 9, 약세, 기, 3월, 며, 2000억원, 집계...","기준, 45, 바, 차, 부가세, 9, 약세, 기, 3월, 며, 2000억원, 집계...",하이트진로,생활소비재,1
3,80,대기업 브랜드 밀맥주 카스 화이트뿐 유흥시장 중심 마케팅에 밀맥주 소홀 가정시장 커...,2023-07-31,"보수적, 나서, 수입맥주, 우리나라, 선도, 유일, 5정도, 사건, 되, 역사, 같...","보수적, 나서, 수입맥주, 우리나라, 선도, 유일, 5정도, 사건, 되, 역사, 같...",하이트진로,생활소비재,1
4,80,켈리 재판매 및 DB 금지 류난영 기자 하이트진로의 맥주 켈리 와 롯데칠성음료의 소...,2023-07-31,"끼치, 바, 4월, 61, 활동, 감소, 증, 74, 풀이, 판매량, 기, 보이, ...","끼치, 바, 4월, 61, 활동, 감소, 증, 74, 풀이, 판매량, 기, 보이, ...",하이트진로,생활소비재,1
...,...,...,...,...,...,...,...,...
132332,402340,LG에너지솔루션 개인 순매수 1위 3일 코스피지수가 1 가까이 하락했다 이날 코스피...,2023-05-03,"업종별, 삼성전기, 엔씨소프트, LIG넥스원, 내리, 하, 화학, 오르, 3, 동반...","업종별, 삼성전기, 엔씨소프트, LIG넥스원, 내리, 화학, 오르, 3, 동반, 대...",SK스퀘어,정보기술,1
132333,402340,투자금은 자산 매각으로 마련하라 SK그룹 투자 신중론 회장 지시 자금 조달 빨간불...,2023-05-03,"나서, 증대, 바, 9월, 며, 적, 떨어지, 기업, 투, 전량, 관계자, 11번,...","나서, 증대, 바, 9월, 며, 적, 떨어지, 기업, 투, 전량, 관계자, 11번,...",SK스퀘어,정보기술,1
132334,402340,차세대 유니콘으로 기대를 받다 경영난으로 고강도 구조조정에 돌입한 그린랩스가 최대주...,2023-05-03,"전무, 교체, 정의민, 나서, 3일, 시, 아시아지역, 방안, 만기연장, 방식, 며...","전무, 교체, 정의민, 나서, 3일, 시, 아시아지역, 방안, 만기연장, 방식, 며...",SK스퀘어,정보기술,1
132335,402340,포스코퓨처엠 개인 순매수 1위 코스피가 2일 외국인과 기관의 매수세에 힘입어 상승하...,2023-05-02,"순매수했다, 업종별, 삼성전기, 순매수하, 삼성중공업, 엔씨소프트, 삼성전자왁, 순...","순매수했다, 업종별, 삼성전기, 순매수하, 삼성중공업, 엔씨소프트, 삼성전자왁, 순...",SK스퀘어,정보기술,1
132336,402340,네이버 카카오 디지털 휴먼 경쟁력은 로지 BTS 이정재 등과 엑스포 홍보대사 카카오...,2023-05-01,"인공지능, 국제, 활동, 기술, 기업, 운영, 메타버스, 공식, 국내, 일상, 카카...","인공지능, 국제, 활동, 기술, 기업, 운영, 메타버스, 공식, 국내, 일상, 카카...",SK스퀘어,정보기술,0

In [ ]:
news['label'].value_counts()

1    81925
0    50411
Name: label, dtype: int64

In [ ]:
news.to_csv("labeled_news.csv")